# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 789bdc8fdf2b09c923b83a4436dd2d3a2a731fcfd1170c207aee333075fa20d8b6c8d2c342b3ad7ccc8446b6bd9a31df5078e6b225a8542a90f64399006f160e

test:
  secret_key_base: aea754ea8f4e22ccea7b0cfe645b09a82e503dce8cca7742a8375069899f806d85a7f6921a8742c8a8a607158e12d19c86396f31d6a43646af4c2e066243e80e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
